# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/work/_pythonProjects/asset_browser/UI/Ui_dbDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(358, 170)
        Dialog.setStyleSheet("/*\n"
"Dark: Dark: #16191d\n"
"Assent1: #1f232a\n"
"Assent2: #2c313c\n"
"Assent3: #343b47\n"
"Text1: #fff\n"
"Text2:#838ea2\n"
" */\n"
"\n"
"\n"
"#header_widget, #window_label, #pushButton{\n"
"background-color: #1f232a;\n"
"color: #838ea2;\n"
"\n"
"}\n"
"\n"
"\n"
"#body_frame, #messeg_label{\n"
"    border:none;\n"
"    background-color:  #16191d;\n"
"    backgroundr: none;\n"
"    padding: 0;\n"
"    margin: 0;\n"
"    color: #fff;\n"
"}\n"
"\n"
"#body_frame QPushButton{\n"
"    border-radius: 10px;\n"
"    background-color:#343b47;\n"
"    height: 20px;\n"
"    color: #838ea2;\n"
"    text-align:left;\n"
"    padding: 0px 20 px;\n"
"}\n"
"\n"
"#body_frame QPushButton:hover{\n"
"    color: #fff;\n"
"}\n"
"\n"
"/*\n"
"QLineEdit, QTextEdit {\n"
"padding: 0 10px;\n"
"background-color:#1f232a;\n"
"border-radius: 10px;\n"
"}\n"
"#centralwidget{\n"
"    background-color: #1f232a;\n"
"}\n"
"#left_panel{\n"
"    background-color:#16191d;\n"
"}\n"
"#left_menu_subcontaner QPushButton{\n"
"    text-align: left;\n"
"    padding: 5px 10px;\n"
"    border-top-left-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"}\n"
" \n"
"\n"
"#drop_frame {\n"
"    background-color:#343b47;\n"
"    border-top-right-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"}\n"
"#search_lineEdit, #add_asset_frame, #Settingf_frame, #info_frame, #tree_frame{\n"
"    background-color:#16191d;\n"
"    border-radius: 10px;\n"
"}\n"
"#add_asset_button{\n"
"    background-color:#2c313c;\n"
"    border-radius: 10px;\n"
"}\n"
"#status_label, #window_label, #help_text_label{\n"
"color: #838ea2;\n"
"}\n"
"\n"
"\n"
"QScrollBar:vertical {\n"
"     border: none;\n"
"    width: 12px;\n"
"    margin: 25px 0 25px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"QScrollBar::handle:vertical {    \n"
"    background: #343b47;\n"
"    min-height: 30px;\n"
"    border-radius: 6px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color:#2c313c;\n"
"}\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: #343b47;;\n"
"    height: 25px;\n"
"    border-radius: 6px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover{    \n"
"    background-color:#2c313c;\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: #343b47;\n"
"    height: 25px;\n"
"    border-radius: 6px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover{    \n"
"    background-color:#2c313c;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background:#16191d;\n"
"}\n"
"")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.header_widget = QtWidgets.QWidget(Dialog)
        self.header_widget.setMaximumSize(QtCore.QSize(16777215, 30))
        self.header_widget.setObjectName("header_widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.header_widget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget_2 = QtWidgets.QWidget(self.header_widget)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setContentsMargins(10, 0, 0, 0)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(20, 20))
        self.pushButton.setMaximumSize(QtCore.QSize(20, 20))
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(24, 24))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.window_label = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.window_label.setFont(font)
        self.window_label.setObjectName("window_label")
        self.horizontalLayout.addWidget(self.window_label)
        self.horizontalLayout_3.addWidget(self.widget_2)
        self.verticalLayout_2.addWidget(self.header_widget)
        self.body_frame = QtWidgets.QFrame(Dialog)
        self.body_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.body_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.body_frame.setObjectName("body_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.body_frame)
        self.horizontalLayout_2.setContentsMargins(15, -1, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.messeg_label = QtWidgets.QLabel(self.body_frame)
        self.messeg_label.setObjectName("messeg_label")
        self.horizontalLayout_2.addWidget(self.messeg_label)
        self.frame_2 = QtWidgets.QFrame(self.body_frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.new_button = QtWidgets.QPushButton(self.frame_2)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/database.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.new_button.setIcon(icon1)
        self.new_button.setObjectName("new_button")
        self.verticalLayout.addWidget(self.new_button)
        self.point_button = QtWidgets.QPushButton(self.frame_2)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/mouse-pointer.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.point_button.setIcon(icon2)
        self.point_button.setObjectName("point_button")
        self.verticalLayout.addWidget(self.point_button)
        self.cancel_button = QtWidgets.QPushButton(self.frame_2)
        self.cancel_button.setMinimumSize(QtCore.QSize(0, 20))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/x-circle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cancel_button.setIcon(icon3)
        self.cancel_button.setIconSize(QtCore.QSize(16, 16))
        self.cancel_button.setObjectName("cancel_button")
        self.verticalLayout.addWidget(self.cancel_button)
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.verticalLayout_2.addWidget(self.body_frame)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.window_label.setText(_translate("Dialog", "Database selection"))
        self.messeg_label.setText(_translate("Dialog", "The program cannot work \n"
"without a database connection. \n"
"You must select a database or  \n"
"create new one."))
        self.new_button.setText(_translate("Dialog", "New database"))
        self.point_button.setText(_translate("Dialog", "Point database"))
        self.cancel_button.setText(_translate("Dialog", "Cancel"))
import resurses_rc
