# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/03_andrey/py_progects/asset_browser/UI/Ui_MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(664, 705)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(0, 0))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.search_lineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.search_lineEdit.setObjectName("search_lineEdit")
        self.horizontalLayout.addWidget(self.search_lineEdit)
        self.search_button = QtWidgets.QPushButton(self.frame_2)
        self.search_button.setObjectName("search_button")
        self.horizontalLayout.addWidget(self.search_button)
        self.create_asset_button = QtWidgets.QPushButton(self.frame_2)
        self.create_asset_button.setObjectName("create_asset_button")
        self.horizontalLayout.addWidget(self.create_asset_button)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.verticalLayout.addWidget(self.frame)
        self.clear_button = QtWidgets.QPushButton(self.centralwidget)
        self.clear_button.setObjectName("clear_button")
        self.verticalLayout.addWidget(self.clear_button)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.galery_frame = QtWidgets.QFrame(self.centralwidget)
        self.galery_frame.setMinimumSize(QtCore.QSize(10, 10))
        self.galery_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.galery_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.galery_frame.setObjectName("galery_frame")
        self.galery_VLayout = QtWidgets.QVBoxLayout(self.galery_frame)
        self.galery_VLayout.setContentsMargins(0, 0, 0, 0)
        self.galery_VLayout.setSpacing(0)
        self.galery_VLayout.setObjectName("galery_VLayout")
        self.verticalLayout.addWidget(self.galery_frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.search_lineEdit.setPlaceholderText(_translate("MainWindow", "Type tag or tags here"))
        self.search_button.setText(_translate("MainWindow", "search asset"))
        self.create_asset_button.setText(_translate("MainWindow", "Create asset"))
        self.clear_button.setText(_translate("MainWindow", "clear"))
        self.pushButton.setText(_translate("MainWindow", "knopka"))
